// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import { DecoManifest } from "$live/types.ts";
import * as $0 from "./routes/[...catchall].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/ecommerce.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/marketing-digital.tsx";
import * as $$0 from "./islands/LiveControls.tsx";
import * as $$$0 from "./sections/Cards.tsx";
import * as $$$1 from "./sections/GetStarted.tsx";
import * as $$$2 from "./sections/Head.tsx";
import * as $$$3 from "./sections/Header.tsx";
import * as $$$4 from "./sections/Hero.tsx";
import * as $$$5 from "./sections/Markdown.tsx";
import * as $$$6 from "./sections/QuillText.tsx";
import * as $$$7 from "./sections/Topbar.tsx";
import * as $$$$0 from "./functions/LoadGitHubRaw.ts";

const manifest: DecoManifest = {
  routes: {
    "./routes/[...catchall].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/ecommerce.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/marketing-digital.tsx": $5,
  },
  islands: { "./islands/LiveControls.tsx": $$0 },
  sections: {
    "./sections/Cards.tsx": $$$0,
    "./sections/GetStarted.tsx": $$$1,
    "./sections/Head.tsx": $$$2,
    "./sections/Header.tsx": $$$3,
    "./sections/Hero.tsx": $$$4,
    "./sections/Markdown.tsx": $$$5,
    "./sections/QuillText.tsx": $$$6,
    "./sections/Topbar.tsx": $$$7,
  },
  functions: { "./functions/LoadGitHubRaw.ts": $$$$0 },
  schemas: {
    "./sections/Cards.tsx": {
      "inputSchema": {
        "title": " Cards",
        "type": "object",
        "properties": {
          "products": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string",
                  "title": "Title",
                },
                "list": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "title": {
                        "type": "string",
                        "title": "Title",
                      },
                    },
                    "required": [
                      "title",
                    ],
                  },
                  "title": "List",
                },
              },
              "required": [
                "title",
                "list",
              ],
            },
            "title": "Products",
          },
        },
        "required": [
          "products",
        ],
      },
      "outputSchema": null,
    },
    "./sections/GetStarted.tsx": {
      "inputSchema": {
        "title": " Get Started",
        "type": "object",
        "properties": {
          "enableInspectVSCode": {
            "type": [
              "boolean",
              "null",
            ],
            "title": "Enable Inspect V S Code",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "./sections/Head.tsx": {
      "inputSchema": {
        "title": " Head",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "title": "Title",
          },
          "description": {
            "type": "string",
            "title": "Description",
          },
          "url": {
            "type": "string",
            "title": "Url",
          },
          "imageUrl": {
            "type": "string",
            "title": "Image Url",
          },
          "faviconUrl": {
            "type": "string",
            "title": "Favicon Url",
          },
          "styleUrls": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Style Urls",
          },
          "themeColor": {
            "type": "string",
            "title": "Theme Color",
          },
        },
        "required": [
          "title",
          "description",
          "url",
          "imageUrl",
          "faviconUrl",
          "styleUrls",
          "themeColor",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Header.tsx": {
      "inputSchema": {
        "title": " Header",
        "type": "object",
        "properties": {
          "logo": {
            "type": "string",
            "title": "Logo",
          },
          "menu": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "text": {
                  "type": "string",
                  "title": "Text",
                },
                "link": {
                  "type": [
                    "string",
                    "null",
                  ],
                  "title": "Link",
                },
              },
              "required": [
                "text",
              ],
            },
            "title": "Menu",
          },
          "button": {
            "title": "Button",
            "type": "object",
            "properties": {
              "text": {
                "type": "string",
                "title": "Text",
              },
              "link": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Link",
              },
            },
            "required": [
              "text",
            ],
          },
        },
        "required": [
          "logo",
          "menu",
          "button",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Hero.tsx": {
      "inputSchema": {
        "title": " Hero",
        "type": "object",
        "properties": {
          "titleH1": {
            "type": "string",
            "title": "Title H1",
          },
          "titleH2": {
            "type": "string",
            "title": "Title H2",
          },
          "textSEO": {
            "type": "string",
            "title": "Text S E O",
          },
          "backgroundImage": {
            "format": "image-uri",
            "type": "string",
            "title": "Background Image",
          },
        },
        "required": [
          "titleH1",
          "titleH2",
          "textSEO",
          "backgroundImage",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Markdown.tsx": {
      "inputSchema": {
        "title": " Markdown",
        "type": "object",
        "properties": {
          "text": {
            "$id": "5b1cd5713a375e18bb93e9635b8a2dc5fc2672cf",
            "format": "live-function",
            "type": "string",
            "title": "Text",
          },
        },
        "required": [
          "text",
        ],
      },
      "outputSchema": null,
    },
    "./sections/QuillText.tsx": {
      "inputSchema": {
        "title": " Quill Text",
        "type": "object",
        "properties": {
          "html": {
            "format": "html",
            "type": "string",
            "title": "Html",
          },
        },
        "required": [
          "html",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Topbar.tsx": {
      "inputSchema": {
        "title": " Topbar",
        "type": "object",
        "properties": {
          "links": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "phone": {
                  "type": "string",
                  "title": "Phone",
                },
                "link": {
                  "type": "string",
                  "title": "Link",
                },
              },
              "required": [
                "phone",
                "link",
              ],
            },
            "title": "Links",
          },
        },
        "required": [
          "links",
        ],
      },
      "outputSchema": null,
    },
    "./functions/LoadGitHubRaw.ts": {
      "inputSchema": {
        "title": " Load Git Hub Raw",
        "type": "object",
        "properties": {
          "repo": {
            "type": "string",
            "title": "Repo",
            "description": "Complete user/repo format",
          },
          "branch": {
            "type": "string",
            "title": "Branch",
            "description": "Branch",
          },
          "path": {
            "type": "string",
            "title": "Path",
            "description":
              "Path to fetch, or leave blank and add :path route param.",
          },
        },
        "required": [
          "repo",
          "branch",
          "path",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "5b1cd5713a375e18bb93e9635b8a2dc5fc2672cf",
          },
        },
        "additionalProperties": true,
      },
    },
  },
  baseUrl: import.meta.url,
  config,
};

// live — this exposes the manifest so the live server can render components dynamically
globalThis.manifest = manifest;

export default manifest;
